#!/bin/sh

while /sbin/setuser abc inotifywait --recursive --event modify /config/apache/site-confs/; do
  sv down /etc/service/web/
  sv up /etc/service/web/
  echo "Default.conf changed, restarting"

done
